### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ramonskie** [robbeofficial/spotifyripper#14]
when trying to download song spotify:track/0Ug6x0wl0Sjmombbtckutr

i get the following error

```
Logging in, please wait...
Logged in!
Loading track...
Loaded track: A Brand New Day - The Wiz/Soundtrack Version
ripping A Brand New Day - The Wiz/Soundtrack Version.mp3 ...Playing
Can't init outfile '/home/klm21904/Workspace/spotifyripper/Diana Ross/The Wiz/A Brand New Day - The Wiz/Soundtrack Version.mp3'
.Traceback (most recent call last):
  File "./jbripper.py", line 152, in <module>
    ripper.connect()
  File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 81, in connect
    self.loop(self.session) # returns on logged out
  File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 97, in loop
    session, *message['args'])
  File "./jbripper.py", line 138, in music_delivery_safe
    rip(session, frames, frame_size, num_frames, sample_type, sample_rate, channels)
  File "./jbripper.py", line 54, in rip
    pipe.write(frames);
IOError: [Errno 32] Broken pipe
```

**Comment by Tak-MK** [comment]
I have that problem too, it fails when the song has any character like / or ( )

**Comment by ramonskie** [comment]
i'm using the @AndersTornkvist fork now

**Comment by Tak-MK** [comment]
Thanks! I'm triying to download that pull request using tutorials but I can't... How did you done it?

Thanks a lot!

**Comment by ramonskie** [comment]
just clone that fork in a new dir and use that instead

```
git clone https://github.com/AndersTornkvist/spotifyripper.git
```

**Comment by Tak-MK** [comment]
Working, thanks!
