### ISSUE TITLE
Does not handle special char " in title names

### ISSUE THREAD

**Issue by davidkarlsen** [robbeofficial/spotifyripper#3]
spotify:track:1jBcfkNUcPzMGYKgGKVoKE

Will lead to:
Loading track...
Loaded track: Big Fun - Original 12" Mix
ripping Big Fun - Original 12" Mix.mp3 ...Playing
/bin/sh: 1: Syntax error: Unterminated quoted string
.Traceback (most recent call last):
  File "./jbripper.py", line 142, in <module>
    ripper.connect()
  File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 81, in connect
    self.loop(self.session) # returns on logged out
  File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 97, in loop
    session, *message['args'])
  File "./jbripper.py", line 128, in music_delivery_safe
    rip(session, frames, frame_size, num_frames, sample_type, sample_rate, channels)
  File "./jbripper.py", line 46, in rip
    pipe.write(frames);
IOError: [Errno 32] Broken pipe
^C

**Comment by AndersTornkvist** [comment]
I believe my pull request #4 fixes this.
