### ISSUE TITLE
spotifyripper seems to crash when track name contains quotes

### ISSUE THREAD

**Issue by Scindix** [robbeofficial/spotifyripper#34]
steps to reproduce:
execute the following command:

```
$ LD_LIBRARY_PATH=/usr/local/lib/ PYTHONPATH=/usr/lib/python2.7/site-packages python2 ./jbripper.py user passwd spotify:track:7y2YUIyCuVhBidENVT0068
```

This generates the following error:

```
[...]
Loading track...
Loaded track: Love Me Like You Do - From "Fifty Shades Of Grey"
ripping Love Me Like You Do - From "Fifty Shades Of Grey".mp3 ...Playing
lame: excess arg Shades
.Traceback (most recent call last):
  File "./jbripper.py", line 152, in <module>
    ripper.connect()
  File "/usr/lib/python2.7/site-packages/spotify/manager/session.py", line 81, in connect
    self.loop(self.session) # returns on logged out
  File "/usr/lib/python2.7/site-packages/spotify/manager/session.py", line 97, in loop
    session, *message['args'])
  File "./jbripper.py", line 138, in music_delivery_safe
    rip(session, frames, frame_size, num_frames, sample_type, sample_rate, channels)
  File "./jbripper.py", line 54, in rip
    pipe.write(frames);
IOError: [Errno 32] Broken pipe
```

It only happens for tracks with quotes in its names.

**Comment by shakisha** [comment]
unable to reproduce on my side. 

Try to set bash env lc_ctype=utf8

**Comment by gabboman** [comment]
It happend to me with this song: spotify:track:5RjrJ55QUiJaGQEee5CYcO 

Solution: I'll try to make a pull request later, but i had to change the appearances from track.name() to track.name().decode('unicode-escape')
