### ISSUE TITLE
Unable to install spotify module on macOS

### ISSUE THREAD

**Issue by phathak** [robbeofficial/spotifyripper#42]
Any ideas?
```
Traceback (most recent call last):
  File "./jbripper.py", line 6, in <module>
    from jukebox import Jukebox, container_loaded
  File "/Users/bruno/spotifyripper/jukebox.py", line 10, in <module>
    from spotify import ArtistBrowser, Link, ToplistBrowser, SpotifyError
ImportError: cannot import name ToplistBrowser

```

**Comment by OrmeAudio** [comment]
Same Problem on Sierra
